library;

const List<(String, String, String)> kCountries = [
  ('AD', 'Andorra', 'Андорра'),
  ('AE', 'United Arab Emirates', 'Объединённые Арабские Эмираты'),
  ('AF', 'Afghanistan', 'Афганистан'),
  ('AG', 'Antigua and Barbuda', 'Антигуа и Барбуда'),
  ('AI', 'Anguilla', 'Ангилья'),
  ('AL', 'Albania', 'Албания'),
  ('AM', 'Armenia', 'Армения'),
  ('AO', 'Angola', 'Ангола'),
  ('AQ', 'Antarctica', 'Антарктида'),
  ('AR', 'Argentina', 'Аргентина'),
  ('AS', 'American Samoa', 'Американское Самоа'),
  ('AT', 'Austria', 'Австрия'),
  ('AU', 'Australia', 'Австралия'),
  ('AW', 'Aruba', 'Аруба'),
  ('AX', 'Åland Islands', 'Аландские острова'),
  ('AZ', 'Azerbaijan', 'Азербайджан'),
  ('BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина'),
  ('BB', 'Barbados', 'Барбадос'),
  ('BD', 'Bangladesh', 'Бангладеш'),
  ('BE', 'Belgium', 'Бельгия'),
  ('BF', 'Burkina Faso', 'Буркина-Фасо'),
  ('BG', 'Bulgaria', 'Болгария'),
  ('BH', 'Bahrain', 'Бахрейн'),
  ('BI', 'Burundi', 'Бурунди'),
  ('BJ', 'Benin', 'Бенин'),
  ('BL', 'Saint Barthélemy', 'Сен-Бартелеми'),
  ('BM', 'Bermuda', 'Бермудские острова'),
  ('BN', 'Brunei', 'Бруней'),
  ('BO', 'Bolivia', 'Боливия'),
  ('BQ', 'Caribbean Netherlands', 'Бонэйр, Синт-Эстатиус и Саба'),
  ('BR', 'Brazil', 'Бразилия'),
  ('BS', 'Bahamas', 'Багамские острова'),
  ('BT', 'Bhutan', 'Бутан'),
  ('BV', 'Bouvet Island', 'Остров Буве'),
  ('BW', 'Botswana', 'Ботсвана'),
  ('BY', 'Belarus', 'Беларусь'),
  ('BZ', 'Belize', 'Белиз'),
  ('CA', 'Canada', 'Канада'),
  ('CC', 'Cocos Islands', 'Кокосовые острова'),
  ('CD', 'DR Congo', 'ДР Конго'),
  ('CF', 'Central African Republic', 'Центральноафриканская Республика'),
  ('CG', 'Republic of the Congo', 'Республика Конго'),
  ('CH', 'Switzerland', 'Швейцария'),
  ('CI', "Côte d'Ivoire", "Кот-д'Ивуар"),
  ('CK', 'Cook Islands', 'Острова Кука'),
  ('CL', 'Chile', 'Чили'),
  ('CM', 'Cameroon', 'Камерун'),
  ('CN', 'China', 'Китай'),
  ('CO', 'Colombia', 'Колумбия'),
  ('CR', 'Costa Rica', 'Коста-Рика'),
  ('CU', 'Cuba', 'Куба'),
  ('CV', 'Cape Verde', 'Кабо-Верде'),
  ('CW', 'Curaçao', 'Кюрасао'),
  ('CX', 'Christmas Island', 'Остров Рождества'),
  ('CY', 'Cyprus', 'Кипр'),
  ('CZ', 'Czechia', 'Чехия'),
  ('DE', 'Germany', 'Германия'),
  ('DJ', 'Djibouti', 'Джибути'),
  ('DK', 'Denmark', 'Дания'),
  ('DM', 'Dominica', 'Доминика'),
  ('DO', 'Dominican Republic', 'Доминиканская Республика'),
  ('DZ', 'Algeria', 'Алжир'),
  ('EC', 'Ecuador', 'Эквадор'),
  ('EE', 'Estonia', 'Эстония'),
  ('EG', 'Egypt', 'Египет'),
  ('EH', 'Western Sahara', 'Западная Сахара'),
  ('ER', 'Eritrea', 'Эритрея'),
  ('ES', 'Spain', 'Испания'),
  ('ET', 'Ethiopia', 'Эфиопия'),
  ('FI', 'Finland', 'Финляндия'),
  ('FJ', 'Fiji', 'Фиджи'),
  ('FK', 'Falkland Islands', 'Фолклендские острова'),
  ('FM', 'Micronesia', 'Микронезия'),
  ('FO', 'Faroe Islands', 'Фарерские острова'),
  ('FR', 'France', 'Франция'),
  ('GA', 'Gabon', 'Габон'),
  ('GB', 'United Kingdom', 'Великобритания'),
  ('GD', 'Grenada', 'Гренада'),
  ('GE', 'Georgia', 'Грузия'),
  ('GF', 'French Guiana', 'Французская Гвиана'),
  ('GG', 'Guernsey', 'Гернси'),
  ('GH', 'Ghana', 'Гана'),
  ('GI', 'Gibraltar', 'Гибралтар'),
  ('GL', 'Greenland', 'Гренландия'),
  ('GM', 'Gambia', 'Гамбия'),
  ('GN', 'Guinea', 'Гвинея'),
  ('GP', 'Guadeloupe', 'Гваделупа'),
  ('GQ', 'Equatorial Guinea', 'Экваториальная Гвинея'),
  ('GR', 'Greece', 'Греция'),
  (
    'GS',
    'South Georgia and the South Sandwich Islands',
    'Южная Георгия и Южные Сандвичевы острова',
  ),
  ('GT', 'Guatemala', 'Гватемала'),
  ('GU', 'Guam', 'Гуам'),
  ('GW', 'Guinea-Bissau', 'Гвинея-Бисау'),
  ('GY', 'Guyana', 'Гайана'),
  ('HK', 'Hong Kong', 'Гонконг'),
  (
    'HM',
    'Heard Island and McDonald Islands',
    'Остров Херд и острова Макдональд',
  ),
  ('HN', 'Honduras', 'Гондурас'),
  ('HR', 'Croatia', 'Хорватия'),
  ('HT', 'Haiti', 'Гаити'),
  ('HU', 'Hungary', 'Венгрия'),
  ('ID', 'Indonesia', 'Индонезия'),
  ('IE', 'Ireland', 'Ирландия'),
  ('IL', 'Israel', 'Израиль'),
  ('IM', 'Isle of Man', 'Остров Мэн'),
  ('IN', 'India', 'Индия'),
  (
    'IO',
    'British Indian Ocean Territory',
    'Британская территория в Индийском океане',
  ),
  ('IQ', 'Iraq', 'Ирак'),
  ('IR', 'Iran', 'Иран'),
  ('IS', 'Iceland', 'Исландия'),
  ('IT', 'Italy', 'Италия'),
  ('JE', 'Jersey', 'Джерси'),
  ('JM', 'Jamaica', 'Ямайка'),
  ('JO', 'Jordan', 'Иордания'),
  ('JP', 'Japan', 'Япония'),
  ('KE', 'Kenya', 'Кения'),
  ('KG', 'Kyrgyzstan', 'Киргизия'),
  ('KH', 'Cambodia', 'Камбоджа'),
  ('KI', 'Kiribati', 'Кирибати'),
  ('KM', 'Comoros', 'Коморские Острова'),
  ('KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис'),
  ('KP', 'North Korea', 'Северная Корея'),
  ('KR', 'South Korea', 'Южная Корея'),
  ('KW', 'Kuwait', 'Кувейт'),
  ('KY', 'Cayman Islands', 'Каймановы острова'),
  ('KZ', 'Kazakhstan', 'Казахстан'),
  ('LA', 'Laos', 'Лаос'),
  ('LB', 'Lebanon', 'Ливан'),
  ('LC', 'Saint Lucia', 'Сент-Люсия'),
  ('LI', 'Liechtenstein', 'Лихтенштейн'),
  ('LK', 'Sri Lanka', 'Шри-Ланка'),
  ('LR', 'Liberia', 'Либерия'),
  ('LS', 'Lesotho', 'Лесото'),
  ('LT', 'Lithuania', 'Литва'),
  ('LU', 'Luxembourg', 'Люксембург'),
  ('LV', 'Latvia', 'Латвия'),
  ('LY', 'Libya', 'Ливия'),
  ('MA', 'Morocco', 'Марокко'),
  ('MC', 'Monaco', 'Монако'),
  ('MD', 'Moldova', 'Молдова'),
  ('ME', 'Montenegro', 'Черногория'),
  ('MF', 'Saint Martin', 'Сен-Мартен'),
  ('MG', 'Madagascar', 'Мадагаскар'),
  ('MH', 'Marshall Islands', 'Маршалловы Острова'),
  ('MK', 'North Macedonia', 'Северная Македония'),
  ('ML', 'Mali', 'Мали'),
  ('MM', 'Myanmar', 'Мьянма'),
  ('MN', 'Mongolia', 'Монголия'),
  ('MO', 'Macao', 'Макао'),
  ('MP', 'Northern Mariana Islands', 'Северные Марианские острова'),
  ('MQ', 'Martinique', 'Мартиника'),
  ('MR', 'Mauritania', 'Мавритания'),
  ('MS', 'Montserrat', 'Монтсеррат'),
  ('MT', 'Malta', 'Мальта'),
  ('MU', 'Mauritius', 'Маврикий'),
  ('MV', 'Maldives', 'Мальдивы'),
  ('MW', 'Malawi', 'Малави'),
  ('MX', 'Mexico', 'Мексика'),
  ('MY', 'Malaysia', 'Малайзия'),
  ('MZ', 'Mozambique', 'Мозамбик'),
  ('NA', 'Namibia', 'Намибия'),
  ('NC', 'New Caledonia', 'Новая Каледония'),
  ('NE', 'Niger', 'Нигер'),
  ('NF', 'Norfolk Island', 'Остров Норфолк'),
  ('NG', 'Nigeria', 'Нигерия'),
  ('NI', 'Nicaragua', 'Никарагуа'),
  ('NL', 'Netherlands', 'Нидерланды'),
  ('NO', 'Norway', 'Норвегия'),
  ('NP', 'Nepal', 'Непал'),
  ('NR', 'Nauru', 'Науру'),
  ('NU', 'Niue', 'Ниуэ'),
  ('NZ', 'New Zealand', 'Новая Зеландия'),
  ('OM', 'Oman', 'Оман'),
  ('PA', 'Panama', 'Панама'),
  ('PE', 'Peru', 'Перу'),
  ('PF', 'French Polynesia', 'Французская Полинезия'),
  ('PG', 'Papua New Guinea', 'Папуа — Новая Гвинея'),
  ('PH', 'Philippines', 'Филиппины'),
  ('PK', 'Pakistan', 'Пакистан'),
  ('PL', 'Poland', 'Польша'),
  ('PM', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон'),
  ('PN', 'Pitcairn Islands', 'Острова Питкэрн'),
  ('PR', 'Puerto Rico', 'Пуэрто-Рико'),
  ('PS', 'Palestine', 'Палестина'),
  ('PT', 'Portugal', 'Португалия'),
  ('PW', 'Palau', 'Палау'),
  ('PY', 'Paraguay', 'Парагвай'),
  ('QA', 'Qatar', 'Катар'),
  ('RE', 'Réunion', 'Реюньон'),
  ('RO', 'Romania', 'Румыния'),
  ('RS', 'Serbia', 'Сербия'),
  ('RU', 'Russia', 'Россия'),
  ('RW', 'Rwanda', 'Руанда'),
  ('SA', 'Saudi Arabia', 'Саудовская Аравия'),
  ('SB', 'Solomon Islands', 'Соломоновы Острова'),
  ('SC', 'Seychelles', 'Сейшельские Острова'),
  ('SD', 'Sudan', 'Судан'),
  ('SE', 'Sweden', 'Швеция'),
  ('SG', 'Singapore', 'Сингапур'),
  ('SH', 'Saint Helena', 'Остров Святой Елены'),
  ('SI', 'Slovenia', 'Словения'),
  ('SJ', 'Svalbard and Jan Mayen', 'Шпицберген и Ян-Майен'),
  ('SK', 'Slovakia', 'Словакия'),
  ('SL', 'Sierra Leone', 'Сьерра-Леоне'),
  ('SM', 'San Marino', 'Сан-Марино'),
  ('SN', 'Senegal', 'Сенегал'),
  ('SO', 'Somalia', 'Сомали'),
  ('SR', 'Suriname', 'Суринам'),
  ('SS', 'South Sudan', 'Южный Судан'),
  ('ST', 'São Tomé and Príncipe', 'Сан-Томе и Принсипи'),
  ('SV', 'El Salvador', 'Сальвадор'),
  ('SX', 'Sint Maarten', 'Синт-Мартен'),
  ('SY', 'Syria', 'Сирия'),
  ('SZ', 'Eswatini', 'Эсватини'),
  ('TC', 'Turks and Caicos Islands', 'Тёркс и Кайкос'),
  ('TD', 'Chad', 'Чад'),
  ('TF', 'French Southern Territories', 'Французские Южные территории'),
  ('TG', 'Togo', ''),
  ('TH', 'Thailand', 'Таиланд'),
  ('TJ', 'Tajikistan', 'Таджикистан'),
  ('TK', 'Tokelau', 'Токелау'),
  ('TL', 'Timor-Leste', 'Восточный Тимор'),
  ('TM', 'Turkmenistan', 'Туркменистан'),
  ('TN', 'Tunisia', 'Тунис'),
  ('TO', 'Tonga', 'Тонга'),
  ('TR', 'Turkey', 'Турция'),
  ('TT', 'Trinidad and Tobago', 'Тринидад и Тобаго'),
  ('TV', 'Tuvalu', 'Тувалу'),
  ('TW', 'Taiwan', 'Тайвань'),
  ('TZ', 'Tanzania', 'Танзания'),
  ('UA', 'Ukraine', 'Украина'),
  ('UG', 'Uganda', 'Уганда'),
  ('UM', 'U.S. Minor Outlying Islands', 'Внешние малые острова США'),
  ('US', 'United States', 'Соединённые Штаты'),
  ('UY', 'Uruguay', 'Уругвай'),
  ('UZ', 'Uzbekistan', 'Узбекистан'),
  ('VA', 'Vatican City', 'Ватикан'),
  ('VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины'),
  ('VE', 'Venezuela', 'Венесуэла'),
  ('VG', 'British Virgin Islands', 'Британские Виргинские острова'),
  ('VI', 'U.S. Virgin Islands', 'Виргинские острова США'),
  ('VN', 'Vietnam', 'Вьетнам'),
  ('VU', 'Vanuatu', 'Вануату'),
  ('WF', 'Wallis and Futuna', 'Уоллис и Футуна'),
  ('WS', 'Samoa', 'Самоа'),
  ('XK', 'Kosovo', 'Косово'),
  ('YE', 'Yemen', 'Йемен'),
  ('YT', 'Mayotte', 'Майотта'),
  ('ZA', 'South Africa', 'Южная Африка'),
  ('ZM', 'Zambia', 'Замбия'),
  ('ZW', 'Zimbabwe', 'Зимбабве'),
];

const Map<String, String> kCountryAliases = {
  'usa': 'US',
  'america': 'US',
  'united states of america': 'US',
  'new york': 'US',
  'new jersey': 'US',
  'los angeles': 'US',
  'san francisco': 'US',
  'silicon valley': 'US',
  'chicago': 'US',
  'dallas': 'US',
  'miami': 'US',
  'seattle': 'US',
  'atlanta': 'US',
  'ashburn': 'US',
  'uk': 'GB',
  'britain': 'GB',
  'great britain': 'GB',
  'england': 'GB',
  'scotland': 'GB',
  'wales': 'GB',
  'london': 'GB',
  'manchester': 'GB',
  'uae': 'AE',
  'emirates': 'AE',
  'dubai': 'AE',
  'korea': 'KR',
  'republic of korea': 'KR',
  'seoul': 'KR',
  'hongkong': 'HK',
  'holland': 'NL',
  'amsterdam': 'NL',
  'rotterdam': 'NL',
  'deutschland': 'DE',
  'frankfurt': 'DE',
  'berlin': 'DE',
  'munich': 'DE',
  'nuremberg': 'DE',
  'falkenstein': 'DE',
  'dusseldorf': 'DE',
  'paris': 'FR',
  'marseille': 'FR',
  'tokyo': 'JP',
  'osaka': 'JP',
  'taipei': 'TW',
  'sydney': 'AU',
  'melbourne': 'AU',
  'toronto': 'CA',
  'montreal': 'CA',
  'vancouver': 'CA',
  'russian federation': 'RU',
  'moscow': 'RU',
  'saint petersburg': 'RU',
  'st petersburg': 'RU',
  'kyiv': 'UA',
  'kiev': 'UA',
  'minsk': 'BY',
  'almaty': 'KZ',
  'astana': 'KZ',
  'yerevan': 'AM',
  'tbilisi': 'GE',
  'baku': 'AZ',
  'tashkent': 'UZ',
  'bishkek': 'KG',
  'stockholm': 'SE',
  'helsinki': 'FI',
  'oslo': 'NO',
  'copenhagen': 'DK',
  'zurich': 'CH',
  'geneva': 'CH',
  'milan': 'IT',
  'rome': 'IT',
  'madrid': 'ES',
  'barcelona': 'ES',
  'lisbon': 'PT',
  'warsaw': 'PL',
  'czech': 'CZ',
  'czech republic': 'CZ',
  'prague': 'CZ',
  'vienna': 'AT',
  'budapest': 'HU',
  'bucharest': 'RO',
  'sofia': 'BG',
  'belgrade': 'RS',
  'athens': 'GR',
  'turkiye': 'TR',
  'türkiye': 'TR',
  'istanbul': 'TR',
  'ankara': 'TR',
  'riga': 'LV',
  'tallinn': 'EE',
  'vilnius': 'LT',
  'dublin': 'IE',
  'brussels': 'BE',
  'reykjavik': 'IS',
  'tel aviv': 'IL',
  'mumbai': 'IN',
  'delhi': 'IN',
  'bangalore': 'IN',
  'jakarta': 'ID',
  'bangkok': 'TH',
  'viet nam': 'VN',
  'hanoi': 'VN',
  'kuala lumpur': 'MY',
  'manila': 'PH',
  'shanghai': 'CN',
  'beijing': 'CN',
  'sao paulo': 'BR',
  'são paulo': 'BR',
  'buenos aires': 'AR',
  'johannesburg': 'ZA',
  'cairo': 'EG',
  'macau': 'MO',
  'burma': 'MM',
  'macedonia': 'MK',
  'bosnia': 'BA',
  'moldavia': 'MD',
  'vatican': 'VA',
  'ivory coast': 'CI',
  "cote d'ivoire": 'CI',
  'drc': 'CD',
  'democratic republic of the congo': 'CD',
  'congo': 'CG',
  'cabo verde': 'CV',
  'curacao': 'CW',
  'reunion': 'RE',
  'aland islands': 'AX',
  'saint barthelemy': 'BL',
  'sao tome and principe': 'ST',
  'east timor': 'TL',
  'swaziland': 'SZ',
  'сша': 'US',
  'америка': 'US',
  'соединённые штаты америки': 'US',
  'нью-йорк': 'US',
  'лос-анджелес': 'US',
  'чикаго': 'US',
  'даллас': 'US',
  'майами': 'US',
  'сиэтл': 'US',
  'англия': 'GB',
  'британия': 'GB',
  'соединённое королевство': 'GB',
  'лондон': 'GB',
  'оаэ': 'AE',
  'эмираты': 'AE',
  'дубай': 'AE',
  'корея': 'KR',
  'сеул': 'KR',
  'кндр': 'KP',
  'голландия': 'NL',
  'амстердам': 'NL',
  'роттердам': 'NL',
  'франкфурт': 'DE',
  'берлин': 'DE',
  'мюнхен': 'DE',
  'нюрнберг': 'DE',
  'париж': 'FR',
  'токио': 'JP',
  'тайбэй': 'TW',
  'сидней': 'AU',
  'торонто': 'CA',
  'рф': 'RU',
  'москва': 'RU',
  'санкт-петербург': 'RU',
  'петербург': 'RU',
  'питер': 'RU',
  'киев': 'UA',
  'белоруссия': 'BY',
  'минск': 'BY',
  'алматы': 'KZ',
  'алма-ата': 'KZ',
  'астана': 'KZ',
  'ереван': 'AM',
  'тбилиси': 'GE',
  'баку': 'AZ',
  'ташкент': 'UZ',
  'кыргызстан': 'KG',
  'бишкек': 'KG',
  'молдавия': 'MD',
  'стокгольм': 'SE',
  'хельсинки': 'FI',
  'осло': 'NO',
  'копенгаген': 'DK',
  'цюрих': 'CH',
  'женева': 'CH',
  'милан': 'IT',
  'рим': 'IT',
  'мадрид': 'ES',
  'барселона': 'ES',
  'лиссабон': 'PT',
  'варшава': 'PL',
  'чешская республика': 'CZ',
  'прага': 'CZ',
  'вена': 'AT',
  'будапешт': 'HU',
  'бухарест': 'RO',
  'белград': 'RS',
  'афины': 'GR',
  'стамбул': 'TR',
  'анкара': 'TR',
  'рига': 'LV',
  'таллин': 'EE',
  'таллинн': 'EE',
  'вильнюс': 'LT',
  'дублин': 'IE',
  'брюссель': 'BE',
  'тель-авив': 'IL',
  'мумбаи': 'IN',
  'дели': 'IN',
  'джакарта': 'ID',
  'бангкок': 'TH',
  'ханой': 'VN',
  'куала-лумпур': 'MY',
  'шанхай': 'CN',
  'пекин': 'CN',
  'сан-паулу': 'BR',
  'буэнос-айрес': 'AR',
  'юар': 'ZA',
  'каир': 'EG',
  'бирма': 'MM',
  'македония': 'MK',
  'конго': 'CG',
  'демократическая республика конго': 'CD',
};
